# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WiFiProvisioning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DialogProvisioning
  pod 'SideMenu', '~> 6.0'
  pod 'CocoaAsyncSocket'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'MBProgressHUD'
  pod 'Alamofire', '~> 5.2'
  pod 'AWSIoT'
  pod 'AWSMobileClient'
  pod 'Pastel'
  pod 'DLRadioButton'
  pod 'AzureIoTHubServiceClient'
  pod 'AzureIoTHubClient'
  
end
