package com.renesas.wifi;

public enum MYEVENT {

    E_INTRO_PERMISSION_ACVITIVY_CALL,
    E_PERMISSION_MAIN_ACVITIVY_CALL,
    E_INTRO_MAIN_ACVITIVY_CALL,
    E_MAIN_PROVISIONING_CALL,
    //E_MAIN_AP_PROVISIONING_CALL,
    E_SHOW_SELECT_REGION_DIALOG,
    E_MAIN_GENERAL_AWSIOT_CALL,
    E_MAIN_ATCMD_AWSIOT_CALL,

    E_SET_CONFIGURATION,
    //E_INTRO_MAIN_ACVITIVY_CALL,

    E_DEVICE_CONNECT_CHECK,
    E_DEVICE_CONNECT_REMOVE_CALLBACK,

    E_CHECK_NETWORK_CONNECT,
    E_TERMINATE_CONNECT_CHECK_SUBSCRIBE,
    E_WIFI_SET_CHECK,

    E_DEVICE_SCAN_TIMEOUT,
    E_SHOW_DEVICE_CONNECT_FAIL_DIALOG,
    E_SHOW_DEVICE_CONNECTING_DIALOG,
    E_DEVICE_CONNECT_WIFI_WPA2,
    E_DEVICE_CONNECT_WIFI_WPA,
    E_DEVICE_CONNECT_WIFI_WEP,
    E_DEVICE_CONNECT_WIFI_OPEN,

    E_NETWORK_SCAN_TIMEOUT,
    E_SHOW_NETWORK_CONNECT_FAIL_DIALOG,
    E_SHOW_NETWORK_CONNECTING_DIALOG,
    E_NETWORK_CONNECT_WIFI_WPA2,
    E_NETWORK_CONNECT_WIFI_WPA,
    E_NETWORK_CONNECT_WIFI_WEP,
    E_NETWORK_CONNECT_WIFI_OPEN,
    E_CONNECT_AP_TRY,
    E_CONNECT_AP_RETRY,
    //E_REQ_RESULT,
    //E_CONNECT_DEVICE_RETRY,
    E_REMOVE_CALLBACK,
    E_PROVISIONING_TIMEOUT,
    E_TERMINATE,

    E_SHOW_AUTH_FAIL_DIALOG,
    E_SHOW_NO_INTERNET_DIALOG,
    E_SHOW_INPUT_PASSWORD_DIALOG,
    E_SHOW_UNKNOWN_ERROR_DIALOG,
    E_SHOW_SUCCESS_DIALOG,
    E_SHOW_COMPLETE_DIALOG,

    E_PING_TIMEOUT_REMOVE_CALLBACK,

    E_BLE_NETWORK_SCAN_TIMEOUT,

}
