package com.renesas.wifi.awsiot;

public enum AWSEVENT {
    E_SET_CONFIGURATION,
    E_INTRO_MAIN_ACVITIVY_CALL,
    E_DEVICE_COMMAND_NO_RESPONSE_REMOVE_CALLBACK,
    E_DEVICE_CONNECT_CHECK,
    E_DEVICE_CONNECT_REMOVE_CALLBACK,
    E_MQTT_REMOVE_CALLBACK,
    E_UPDATE_SHADOW_NO_RESPONSE_REMOVE_CALLBACK,
    E_CHECK_NETWORK_CONNECT,
    E_CONNECT_CHECK_PUBLISH,
    E_CONNECT_CHECK_SUBSCRIBE,
    E_TERMINATE_CONNECT_CHECK_SUBSCRIBE,
    E_WIFI_SET_CHECK,
    E_GET_SHADOW,
    E_STOP_GET_SHADOW,
    E_REMOVE_CALLBACK,
    E_PROVISIONING_TIMEOUT,

    E_AUTO_TEST,

    E_DEVICE_OPEN_NO_RESPONSE_REMOVE_CALLBACK,
    E_DEVICE_CLOSE_NO_RESPONSE_REMOVE_CALLBACK,
    E_DEVICE_LEDON_NO_RESPONSE_REMOVE_CALLBACK,
    E_DEVICE_LEDOFF_NO_RESPONSE_REMOVE_CALLBACK,
    E_UPDATE_SENSOR_NO_RESPONSE_REMOVE_CALLBACK,
    E_DOOR_OPEN_TIMEOVER,
    E_UPDATE_SENSOR,
    E_STOP_UPDATE_SENSOR,
    E_UPDATE_MONITOR,
    E_DEVICE_CONNECT_TIMEOUT,
    E_MQTT_REMOVE_CALLBACK_MONITOR,
    E_DEVICE_CONNECT_REMOVE_CALLBACK_MONITOR,
    E_GET_SHADOW_MONITOR,
    E_UPDATE_SENSOR_MONITOR,
    E_STOP_GET_SHADOW_MONITOR,
    E_STOP_UPDATE_SENSOR_MONITOR,

    E_SHOW_BATTERY_ALERT,
    E_SHOW_TEMPERATURE_ALERT,

}
