package com.renesas.wifi.azureiot;

public enum AZUREEVENT {
    E_QUERY_DEVICE_TWIN,
    E_DEVICE_CONNECT_CHECK,
    E_DEVICE_CONNECT_TIMEOUT,
    E_DEVICE_CONNECT_REMOVE_CALLBACK,
    E_DEVICE_OPEN_NO_RESPONSE_REMOVE_CALLBACK,
    E_DEVICE_CLOSE_NO_RESPONSE_REMOVE_CALLBACK,
    E_UPDATE_SENSOR_NO_RESPONSE_REMOVE_CALLBACK,
    E_AUTO_TEST,
    E_SHOW_BATTERY_ALERT,
    E_SHOW_TEMPERATURE_ALERT,
    E_DEVICE_COMMAND_NO_RESPONSE_REMOVE_CALLBACK,  //for AT-CMD
}
